# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'PlayWithMind' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CollectionViewFlowLayoutTest

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Fabric', '~> 1.7.9'
pod 'Crashlytics', '~> 3.10.5'
pod 'Firebase/Crash'

end
